# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Henry Tao"
description: > # this means to ignore newlines until "email:"
  I am a fullstack engineer at MySQUAR. I am passion about building awesome products, also rock in Javascript, NodeJS and AngularJS. 

email: hi@henrytao.me
#blog logo
logo: "/assets/images/henry-logo.png"
# blog cover
cover: "/assets/images/creatives-desk.jpg"

name: 'Henry Tao'
author: 'Henry Tao'
author_image: "/assets/images/henry-logo.png"

paginate:	5

url: "http://henrytao.me" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  # - icon:	twitter
  #   url:	https://twitter.com/dirkfabisch
  #   desc: Follow me on twitter
  #   share_url: http://twitter.com/share
  #   share_title: ?text=
  #   share_link: "&amp;url="

  # - icon:	facebook
  #   url:	https://facebook.com/SquarMyanmar
  #   desc: Connect with us on Facebook
  #   share_url: //www.facebook.com/sharer.php
  #   share_title: ?t=
  #   share_link: "&amp;u="

  # - icon:	github
  #   url:	https://github.com/dirkfabisch
  #   desc:	Fork me on github
  #   share_url:
  #   share_title:
  #   share_link:

  # - icon:	google-plus
  #   url:	https://google.com/???
  #   desc:	Add me on google+
  #   share_url:
  #   share_title:
  #   share_link:
