# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "MySQUAR Challenge"
description: > # this means to ignore newlines until "email:"
  We are looking for awesome developers (like you) to join us at MySQUAR. Check out some of our challenges below, push it to GitHub, and show us what you have got. 

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/mysquar-logo.jpg"
# blog cover
cover: "/assets/images/mysquar-challenge-banner.jpg"

name: 'MySQUAR'
author: 'MySQUAR'
author_image: "/assets/images/mysquar-logo.jpg"

paginate:	5

url: "http://challenge.mysquar.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  # - icon:	twitter
  #   url:	https://twitter.com/dirkfabisch
  #   desc: Follow me on twitter
  #   share_url: http://twitter.com/share
  #   share_title: ?text=
  #   share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/SquarMyanmar
    desc: Connect with us on Facebook
    share_url: //www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  # - icon:	github
  #   url:	https://github.com/dirkfabisch
  #   desc:	Fork me on github
  #   share_url:
  #   share_title:
  #   share_link:

  # - icon:	google-plus
  #   url:	https://google.com/???
  #   desc:	Add me on google+
  #   share_url:
  #   share_title:
  #   share_link:
